-- Estrutura mínima de exemplo para Supabase + pgvector
-- Ajuste dimensões de acordo com o modelo de embeddings utilizado.

create extension if not exists vector;

create table if not exists documents (
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb default '{}'::jsonb,
  embedding vector(1536)
);

create or replace function match_documents (
  query_embedding vector(1536),
  match_count int default 4
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language sql stable
as $$
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  order by documents.embedding <=> query_embedding
  limit match_count;
$$;

-- Observação:
-- O workflow de atendimento incluído é uma referência visual de portfólio.
-- Para busca vetorial real, gere o embedding da pergunta e envie query_embedding
-- para a função match_documents.
